### PR TITLE
Add site instructions

### PR DESCRIPTION
**Pull request by markdamobi**
I added functionality so that when you hover over momo, some instructions come up as a modal. checkout my branch and see what it looks like. Feel free to tweak the instructions. If you have opinions on what else to add to that or a different style, or whatever, let me know.

### CODE REVIEW

**Comment by tra38** [comment]
I would like it if there is some indicator that you need to hover over the owl to get advice on how to use the app.

**Comment by markdamobi** [comment]
good idea. I'll look into that.

**Comment by chagers** [comment]
Just a couple of notes! Explained in bullet points, and adjusted text posted below.
- In Functionality, missing a period at end of 1.
- In Color 1 & 2, change 'the' to 'then'. 4 - occurrence misspelled. In last line of instructions, recommend changing 'is' to 'will be'.

Functionality
To get started, just type a word in the search field to see where it's being used on twitter around the world.
1. Search for hashtags!
2. Search for an entire phrase!
3. Search for 2 words at the same time! Simply separate the words using a comma in the search field.
4. Search for multiple words in 1 tweet! Simply separate the words with a space.

Colors
For single word search:
1. If color is dark blue, then it's a negative emotion.
2. If color is light blue, then it's a positive emotion.
3. If the shade of blue is neutral, then the emotion is neutral.

Double word search follows the same rule, but the second word will be shades of red.

**Comment by markdamobi** [comment]
Failed attempt to add speech bubble to momo. I also attempted the bounce effect, but that was acting weird. 
Some other person can go ahead an attempt this. 
@tra38 @chagers @egarreau @mgalicer

**Comment by chagers** [comment]
Closing this pull, as I've incorporated the site instructions into my branch that also adds movement to momo.

**Pull request closed without merging**
